### ISSUE TITLE
Handle lxml unicode error

### ISSUE THREAD

**Issue by hiddenillusion** [williballenthin/process-forest#9]
I have a few evtx files were the `record_xml` being passed to `to_lxml()` is unicode, with no odd characters. LXML (3.7.3) spits the following out:

```
$ python process-forest/src/process_forest.py SYSMON%4OPERATIONAL.EVTX summary
INFO:process-forest.global:using evtx log file
DEBUG:Evtx.Evtx:FILE HEADER at 0x0.
DEBUG:Evtx.Evtx:CHUNK HEADER at 0x1000.
DEBUG:Evtx.Evtx:Record at 0x1200.
Traceback (most recent call last):
  File "process-forest/src/process_forest.py", line 483, in <module>
    main()
  File "process-forest/src/process_forest.py", line 461, in main
    analyzer.analyze(get_entries_with_eids(evtx, set([4688, 4689, 1, 5])))
  File "process-forest/src/process_forest.py", line 211, in analyze
    for entry in entries:
  File "process-forest/src/process_forest.py", line 193, in get_entries_with_eids
    for entry in get_entries(evtx):
  File "process-forest/src/process_forest.py", line 183, in get_entries
    yield Entry(xml, record)
  File "process-forest/src/process_forest.py", line 73, in __init__
    self._node = to_lxml(self._xml)
  File "process-forest/src/process_forest.py", line 25, in to_lxml
    record_xml.replace("xmlns=\"http://schemas.microsoft.com/win/2004/08/events/event\"", ""))
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79010)
  File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118282)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

One possible solution, at least for this instance, is to wrap return in `to_lxml()`, catch the ValueError & manually set the `etree.XMLParser` to use `utf-8` encoding and manually encode `record_lxml.replace()` as well 

```python
...
    except ValueError:
        utf8_parser = etree.XMLParser(encoding='utf-8')
        return etree.fromstring("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>%s" % record_xml.replace("xmlns=\"http://schemas.microsoft.com/win/2004/08/events/event\"", "").encode('utf-8'), parser=utf8_parser)
```

or just manually encode w/o defining a new parser
```python
...
return etree.fromstring("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>%s" % record_xml.replace("xmlns=\"http://schemas.microsoft.com/win/2004/08/events/event\"", "").encode('utf-8'))
```

**Comment by williballenthin** [comment]
I like the first suggestion, where we explicitly declare the xml parser encoding, and the encoding of the xml string. it seems we should do this for all records, not just the ones that fail. would you put together a PR with this fix, after demonstrating it works for your sample?

**Comment by kolayne** [comment]
I am using the very latest version of the project, but get the same error:
```
INFO:process-forest.global:using evtx log file
DEBUG:Evtx.Evtx:FILE HEADER at 0x0.
DEBUG:Evtx.Evtx:CHUNK HEADER at 0x1000.
DEBUG:Evtx.Evtx:Record at 0x1200.
Traceback (most recent call last):
  File "process-forest/src/process_forest.py", line 504, in <module>
    main()
  File "process-forest/src/process_forest.py", line 482, in main
    analyzer.analyze(get_entries_with_eids(evtx, set([4688, 4689, 1, 5])))
  File "process-forest/src/process_forest.py", line 222, in analyze
    for entry in entries:
  File "process-forest/src/process_forest.py", line 203, in get_entries_with_eids
    for entry in get_entries(evtx):
  File "process-forest/src/process_forest.py", line 193, in get_entries
    yield Entry(xml, record)
  File "process-forest/src/process_forest.py", line 78, in __init__
    self._node = to_lxml(self._xml)
  File "process-forest/src/process_forest.py", line 25, in to_lxml
    return etree.fromstring("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>%s" %
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```
I think this should be reopened, shouldn't it?

**Comment by kolayne** [comment]
UPD: I haven't read any other parts of code and haven't worked with `lxml`/`Evtx`/etc, so I don't know how good or crutchy this solution is, but I've fixed the issue by editing `src/process_forest.py:25` (adding the `b` character to use `bytes` instead of `str`):
```python3
    return etree.fromstring(b"<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>%s" %
```

P. S. But if you find this solution good, I would be glad to be a co-author of a commit fixing this :)

**Comment by JLT032** [comment]
same problem with master version of today, i'd very much appreciate a fix :)
i can confirm adding b to the formstring works for me too
